version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
  frontend_tests:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/solo/frontend
    steps:
      - checkout:
          path: ~/solo
      - restore_cache:
          keys:
             - frontend-dependencies-{{ checksum "~/solo/frontend/package.json" }}
      - run:
          name: Run CI
          command: 'npm ci'
      - save_cache:
          paths:
              - ~/solo/frontend/node_modules
          key: frontend-dependencies-{{ checksum "~/solo/frontend/package.json" }}
      - run:
          name: Run Linter
          command: 'npm run lint'
      - run:
          name: Run Typechecker
          command: 'npm run typecheck'
      - run:
          name: Run Tests
          command: 'npm test'
      - snyk/scan:
         monitor-on-build: false
      

  backend_tests:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/solo/backend
    steps:
      - checkout:
          path: ~/solo
      - restore_cache:
          keys:
             - backend-dependencies-{{ checksum "~/solo/backend/requirements/requirements.dev.txt" }}
      - run:
          name: Install Dependencies
          command: 'pip install -r ~/solo/backend/requirements/requirements.dev.txt --user'
      - save_cache:
          paths:
              - /usr/local/lib/python3.8/site-packages
          key: backend-dependencies-{{ checksum "~/solo/backend/requirements/requirements.dev.txt" }}
      - run:
          name: Run Linter
          command: 'pylint backend'
      - run:
          name: Run Code Style Checks
          command: 'black --check .'
      - run:
          name: Run Tests
          command: 'python manage.py test'
      - snyk/scan:
          monitor-on-build: false 
          additional-arguments: --packageManager=pip
          target-file: requirements/requirements.dev.txt
          
      
      

workflows:
  build_and_test:
    jobs:
        - frontend_tests
        - backend_tests


