version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/solo/frontend
    steps:
      - checkout:
          path: ~/solo
      - run:
          name: Run CI
          command: 'npm ci'
      - run:
          name: Run Linter
          command: 'npm run lint'
      - run: 
          name: Run Typechecker
          command: 'npm run typecheck'
      - run: 
          name: Run Tests
          command: 'npm test'
