version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/solo/frontend
    steps:
      - checkout:
          path: ~/solo
      - run:
          name: Run CI
          command: 'npm ci'
      - run:
          name: Run Linter
          command: 'npm run lint'
      - run: 
          name: Run Typechecker
          command: 'npm run typecheck'
      - run: 
          name: Run Tests
          command: 'npm test'
  backend:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/solo/backend
    steps:
      - checkout:
          path: ~/solo
      - restore_cache:
          keys:
             - v1-dependecies-{{ checksum "~/solo/backend/requirements/requirements.txt"}}
             - v1-dependencies-
      - run:
          name: install dependencies
          command: 'pip install -r ~/solo/requirements/requirements.txt --user'
      - save_cache:
          paths:
              - ~/solo/requirements/requirements.txt
          key: v1-dependencies-{{checksum "~/solo/requirements/requirements.txt"}}
      - run:
          name: run tests
          command: 'python manage.py test'
      - run:
          name: run linter
          command: 'pylint backend/'
workflows:
  version: 2
  build_and_test:
    jobs:
        - build
        - backend
  
