version: '3.4'

services:
  backend:
    volumes:
      - ../../backend:/app/
  
  nginx:
    environment: 
      - NGINX_TEMPLATE=http
  
  frontend:
    build:
      context: ../../frontend
      target: build_stage
    command: "npm run start"
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend/src:/app/src
    env_file: 
      - ./.env
    environment: 
      - REACT_APP_API_DOMAIN=$API_DOMAIN
      - REACT_APP_API_PROTOCOL=http